### ISSUE TITLE
trying to run using podman.

### ISSUE THREAD

**Issue by tazihad** [amirdaaee/cloudflare-warp-docker#1]
I get this error. can you help pls? I am using fedora silverblue.  

```
$ podman run -d --name warp -p 127.0.0.1:40000:40000 --cap-add NET_ADMIN --sysctl net.ipv4.conf.eth0.route_localnet=1 --restart unless-stopped amirdaaee/cloudflare-warp:latest
✔ docker.io/amirdaaee/cloudflare-warp:latest
Trying to pull docker.io/amirdaaee/cloudflare-warp:latest...
Getting image source signatures
Copying blob d8a369c9b1e4 done  
Copying blob d6103fce295f done  
Copying blob 2238450926aa done  
Copying blob f390d05e64fe done  
Copying blob 2d0172371d28 done  
Copying blob bc7bbf8dd281 done  
Copying blob ca1c91044c80 done  
Copying blob 8c02d311b645 done  
Copying config 16731416fb done  
Writing manifest to image destination
Storing signatures
Error: crun: open /proc/sys/net/ipv4/conf/eth0/route_localnet: No such file or directory: OCI runtime attempted to invoke a command that was not found

```

I also tried other commands  
```
$ podman run -d --name warp -p 127.0.0.1:9004:8000 --cap-add NET_ADMIN --sysctl net.ipv4.ip_forward=1 --restart unless-stopped amirdaaee/cloudflare-warp:latest
fcf15a91b3f77d6069caa03eb01ab3aa5875b0d65ea279bc640fd8b0eb4c3c20
```

it worked. but i couldn't access the network.  I used proxyomega and set http proxy 127.0.0.1:9004. but not working. any solution?

**Comment by amirdaaee** [comment]
i have made breaking changes to this image in https://github.com/amirdaaee/cloudflare-warp-docker/commit/db4c8ff6b0ea99ac0711b76dbe0d02f4cc2a2621 , but shamefully i didn't update readme (my bad).
you can access **SOCKS** proxy on port 1080 and **HTTP** proxy on 8080.

regards.

**Comment by tazihad** [comment]
@amirdaaee Unfortunately it's not working. 
with this command i was able to start the container. But proxy won't route through the container.  
```
podman run -d --name warp -p 127.0.0.1:40000:40000 --cap-add NET_ADMIN --sysctl net.ipv4.ip_forward=1 --restart unless-stopped amirdaaee/cloudflare-warp:latest
```

**Comment by amirdaaee** [comment]
use this:
```podman run -d --name warp -p 127.0.0.1:1080:1080 -p 127.0.0.1:8080:8080 --restart unless-stopped amirdaaee/cloudflare-warp:latest```
```--cap-add NET_ADMIN``` and ```--sysctl net.ipv4.ip_forward=1``` is no more needed.
proxy would be accessible on:
- socks5://127.0.0.1:1080
- http://127.0.0.1:8080

**Comment by tazihad** [comment]
@amirdaaee Thank you so much man. That worked for me. I hope you keep the warp package update.
