### ISSUE TITLE
Can Support for Passwords in HTTP/Socks5 Proxies Be Added?

### ISSUE THREAD

**Issue by Caringor** [amirdaaee/cloudflare-warp-docker#4]
Hello, I recently had a need to convert Warp's network into HTTP and Socks5 proxies, so I chose your image. However, I noticed that this image does not seem to support setting usernames and passwords for HTTP/Socks5 proxies. I was wondering if it might be possible to add this feature?

**Comment by amirdaaee** [comment]
Hey @Caringor 
this warp image utilizes v2ray proxy to manage http/socks proxy. you can mount a modified version of [v2f-config.json](https://github.com/amirdaaee/cloudflare-warp-docker/blob/master/v2f-config.json) into /etc/v2ray/v2f-config.json to add authentication capabilities.
you can read more about this config file [here](https://www.v2fly.org/config/protocols/http.html#inboundconfigurationobject).
